using NezihBankMAUI.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NezihBankMAUI.Services
{
    internal interface IDistrictService
    {
        List<District> GetDistricts();

        List<District> GetDistrictsbyIlId(int ilId);

    }

    class DistrictService : IDistrictService
    {
        public List<District> GetDistricts()
        {
            return new List<District>()
            {
                new District() { Id = 1, Ad = "Merkez", IlId = 1 },
                new District() { Id = 2, Ad = "Diğer", IlId = 1 },
                new District() { Id = 1, Ad = "Merkez", IlId = 2 },
                new District() { Id = 1, Ad = "Diğer", IlId = 2 },
                new District() { Id = 1, Ad = "Merkez", IlId = 3 },
                new District() { Id = 1, Ad = "Diğer", IlId = 3 },
                new District() { Id = 1, Ad = "Merkez", IlId = 4 },
                new District() { Id = 1, Ad = "Diğer", IlId = 4 },
                new District() { Id = 1, Ad = "Merkez", IlId = 5 },
                new District() { Id = 1, Ad = "Diğer", IlId = 5 },
                new District() { Id = 1, Ad = "Merkez", IlId = 6 },
                new District() { Id = 1, Ad = "Diğer", IlId = 6 },
                new District() { Id = 1, Ad = "Merkez", IlId = 7 },
                new District() { Id = 1, Ad = "Diğer", IlId = 7 },
                new District() { Id = 1, Ad = "Merkez", IlId = 8 },
                new District() { Id = 1, Ad = "Diğer", IlId = 8 },
                new District() { Id = 1, Ad = "Merkez", IlId = 9 },
                new District() { Id = 1, Ad = "Diğer", IlId = 9 },
                new District() { Id = 1, Ad = "Merkez", IlId = 10 },
                new District() { Id = 1, Ad = "Diğer", IlId = 10 },
                new District() { Id = 1, Ad = "Merkez", IlId = 11 },
                new District() { Id = 1, Ad = "Diğer", IlId = 11 },
                new District() { Id = 1, Ad = "Merkez", IlId = 12 },
                new District() { Id = 1, Ad = "Diğer", IlId = 12 },
                new District() { Id = 1, Ad = "Merkez", IlId = 13 },
                new District() { Id = 1, Ad = "Diğer", IlId = 13 },
                new District() { Id = 1, Ad = "Merkez", IlId = 14 },
                new District() { Id = 1, Ad = "Diğer", IlId = 14 },
                new District() { Id = 1, Ad = "Merkez", IlId = 15 },
                new District() { Id = 1, Ad = "Diğer", IlId = 15 },
                new District() { Id = 1, Ad = "Merkez", IlId = 16 },
                new District() { Id = 1, Ad = "Diğer", IlId = 16 },
                new District() { Id = 1, Ad = "Merkez", IlId = 17 },
                new District() { Id = 1, Ad = "Diğer", IlId = 17 },
                new District() { Id = 1, Ad = "Merkez", IlId = 18 },
                new District() { Id = 1, Ad = "Diğer", IlId = 18 },
                new District() { Id = 1, Ad = "Merkez", IlId = 19 },
                new District() { Id = 1, Ad = "Diğer", IlId = 19 },
                new District() { Id = 1, Ad = "Merkez", IlId = 20 },
                new District() { Id = 1, Ad = "Diğer", IlId = 20 },
                new District() { Id = 1, Ad = "Merkez", IlId = 21 },
                new District() { Id = 1, Ad = "Diğer", IlId = 21 },
                new District() { Id = 1, Ad = "Merkez", IlId = 22 },
                new District() { Id = 1, Ad = "Diğer", IlId = 22 },
                new District() { Id = 1, Ad = "Merkez", IlId = 23 },
                new District() { Id = 1, Ad = "Diğer", IlId = 23 },
                new District() { Id = 1, Ad = "Merkez", IlId = 24 },
                new District() { Id = 1, Ad = "Diğer", IlId = 24 },
                new District() { Id = 1, Ad = "Merkez", IlId = 25 },
                new District() { Id = 1, Ad = "Diğer", IlId = 25 },
                new District() { Id = 1, Ad = "Merkez", IlId = 26 },
                new District() { Id = 1, Ad = "Diğer", IlId = 26 },
                new District() { Id = 1, Ad = "Merkez", IlId = 27 },
                new District() { Id = 1, Ad = "Diğer", IlId = 27 },
                new District() { Id = 1, Ad = "Merkez", IlId = 28 },
                new District() { Id = 1, Ad = "Diğer", IlId = 28 },
                new District() { Id = 1, Ad = "Merkez", IlId = 29 },
                new District() { Id = 1, Ad = "Diğer", IlId = 29 },
                new District() { Id = 1, Ad = "Merkez", IlId = 30 },
                new District() { Id = 1, Ad = "Diğer", IlId = 30 },
                new District() { Id = 1, Ad = "Merkez", IlId = 31 },
                new District() { Id = 1, Ad = "Diğer", IlId = 31 },
                new District() { Id = 1, Ad = "Merkez", IlId = 32 },
                new District() { Id = 1, Ad = "Diğer", IlId = 32 },
                new District() { Id = 1, Ad = "Merkez", IlId = 33 },
                new District() { Id = 1, Ad = "Diğer", IlId = 33 },
                new District() { Id = 1, Ad = "Merkez", IlId = 34 },
                new District() { Id = 1, Ad = "Diğer", IlId = 34 },
                new District() { Id = 1, Ad = "Merkez", IlId = 35 },
                new District() { Id = 1, Ad = "Diğer", IlId = 35 },
                new District() { Id = 1, Ad = "Merkez", IlId = 36 },
                new District() { Id = 1, Ad = "Diğer", IlId = 36 },
                new District() { Id = 1, Ad = "Merkez", IlId = 37 },
                new District() { Id = 1, Ad = "Diğer", IlId = 37 },
                new District() { Id = 1, Ad = "Merkez", IlId = 38 },
                new District() { Id = 1, Ad = "Diğer", IlId = 38 },
                new District() { Id = 1, Ad = "Merkez", IlId = 39 },
                new District() { Id = 1, Ad = "Diğer", IlId = 39 },
                new District() { Id = 1, Ad = "Merkez", IlId = 40 },
                new District() { Id = 1, Ad = "Diğer", IlId = 40 },
                new District() { Id = 1, Ad = "Merkez", IlId = 41 },
                new District() { Id = 1, Ad = "Diğer", IlId = 41 },
                new District() { Id = 1, Ad = "Merkez", IlId = 42 },
                new District() { Id = 1, Ad = "Diğer", IlId = 42 },
                new District() { Id = 1, Ad = "Merkez", IlId = 43 },
                new District() { Id = 1, Ad = "Diğer", IlId = 43 },
                new District() { Id = 1, Ad = "Merkez", IlId = 44 },
                new District() { Id = 1, Ad = "Diğer", IlId = 44 },
                new District() { Id = 1, Ad = "Merkez", IlId = 45 },
                new District() { Id = 1, Ad = "Diğer", IlId = 45 },
                new District() { Id = 1, Ad = "Merkez", IlId = 46 },
                new District() { Id = 1, Ad = "Diğer", IlId = 46 },
                new District() { Id = 1, Ad = "Merkez", IlId = 47 },
                new District() { Id = 1, Ad = "Diğer", IlId = 47 },
                new District() { Id = 1, Ad = "Merkez", IlId = 48 },
                new District() { Id = 1, Ad = "Diğer", IlId = 48 },
                new District() { Id = 1, Ad = "Merkez", IlId = 49 },
                new District() { Id = 1, Ad = "Diğer", IlId = 49 },
                new District() { Id = 1, Ad = "Merkez", IlId = 50 },
                new District() { Id = 1, Ad = "Diğer", IlId = 50 },
                new District() { Id = 1, Ad = "Merkez", IlId = 51 },
                new District() { Id = 1, Ad = "Diğer", IlId = 51 },
                new District() { Id = 1, Ad = "Merkez", IlId = 52 },
                new District() { Id = 1, Ad = "Diğer", IlId = 52 },
                new District() { Id = 1, Ad = "Merkez", IlId = 53 },
                new District() { Id = 1, Ad = "Diğer", IlId = 53 },
                new District() { Id = 1, Ad = "Merkez", IlId = 54 },
                new District() { Id = 1, Ad = "Diğer", IlId = 54 },
                new District() { Id = 1, Ad = "Merkez", IlId = 55 },
                new District() { Id = 1, Ad = "Diğer", IlId = 55 },
                new District() { Id = 1, Ad = "Merkez", IlId = 56 },
                new District() { Id = 1, Ad = "Diğer", IlId = 56 },
                new District() { Id = 1, Ad = "Merkez", IlId = 57 },
                new District() { Id = 1, Ad = "Diğer", IlId = 57 },
                new District() { Id = 1, Ad = "Merkez", IlId = 58 },
                new District() { Id = 1, Ad = "Diğer", IlId = 58 },
                new District() { Id = 1, Ad = "Merkez", IlId = 59 },
                new District() { Id = 1, Ad = "Diğer", IlId = 59 },
                new District() { Id = 1, Ad = "Merkez", IlId = 60 },
                new District() { Id = 1, Ad = "Diğer", IlId = 60 },
                new District() { Id = 1, Ad = "Merkez", IlId = 61 },
                new District() { Id = 1, Ad = "Diğer", IlId = 61 },
                new District() { Id = 1, Ad = "Merkez", IlId = 62 },
                new District() { Id = 1, Ad = "Diğer", IlId = 62 },
                new District() { Id = 1, Ad = "Merkez", IlId = 63 },
                new District() { Id = 1, Ad = "Diğer", IlId = 63 },
                new District() { Id = 1, Ad = "Merkez", IlId = 64 },
                new District() { Id = 1, Ad = "Diğer", IlId = 64 },
                new District() { Id = 1, Ad = "Merkez", IlId = 65 },
                new District() { Id = 1, Ad = "Diğer", IlId = 65 },
                new District() { Id = 1, Ad = "Merkez", IlId = 66 },
                new District() { Id = 1, Ad = "Diğer", IlId = 66 },
                new District() { Id = 1, Ad = "Merkez", IlId = 67 },
                new District() { Id = 1, Ad = "Diğer", IlId = 67 },
                new District() { Id = 1, Ad = "Merkez", IlId = 68 },
                new District() { Id = 1, Ad = "Diğer", IlId = 68 },
                new District() { Id = 1, Ad = "Merkez", IlId = 69 },
                new District() { Id = 1, Ad = "Diğer", IlId = 69 },
                new District() { Id = 1, Ad = "Merkez", IlId = 70 },
                new District() { Id = 1, Ad = "Diğer", IlId = 70 },
                new District() { Id = 1, Ad = "Merkez", IlId = 71 },
                new District() { Id = 1, Ad = "Diğer", IlId = 71 },
                new District() { Id = 1, Ad = "Merkez", IlId = 72 },
                new District() { Id = 1, Ad = "Diğer", IlId = 72 },
                new District() { Id = 1, Ad = "Merkez", IlId = 73 },
                new District() { Id = 1, Ad = "Diğer", IlId = 73 },
                new District() { Id = 1, Ad = "Merkez", IlId = 74 },
                new District() { Id = 1, Ad = "Diğer", IlId = 74 },
                new District() { Id = 1, Ad = "Merkez", IlId = 75 },
                new District() { Id = 1, Ad = "Diğer", IlId = 75 },
                new District() { Id = 1, Ad = "Merkez", IlId = 76 },
                new District() { Id = 1, Ad = "Diğer", IlId = 76 },
                new District() { Id = 1, Ad = "Merkez", IlId = 77 },
                new District() { Id = 1, Ad = "Diğer", IlId = 77 },
                new District() { Id = 1, Ad = "Merkez", IlId = 78 },
                new District() { Id = 1, Ad = "Diğer", IlId = 78 },
                new District() { Id = 1, Ad = "Merkez", IlId = 79 },
                new District() { Id = 1, Ad = "Diğer", IlId = 79 },
                new District() { Id = 1, Ad = "Merkez", IlId = 80 },
                new District() { Id = 1, Ad = "Diğer", IlId = 80 },
                new District() { Id = 1, Ad = "Merkez", IlId = 81 },
                new District() { Id = 1, Ad = "Diğer", IlId = 81 },
            };
        }

        public List<District> GetDistrictsbyIlId(int ilId)
        {
            var districts = GetDistricts();

            return districts
                .Where(x => x.IlId == ilId)
                .OrderBy(x => x.Ad)
                .ToList();
        }
    }
}
